### ISSUE TITLE
[PE-D][Tester B] hide patients example error

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T17-4/tp#198]
example doesnt work

I think the team forgot to put n/

![image.png](https://raw.githubusercontent.com/Marcusgwj/ped/main/files/93ab1a0d-6c26-4236-b844-bd6bbfc45044.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Marcusgwj/ped#2

**Comment by Guanzhou03** [comment]
Documentation bug, example should include n/
