### ISSUE TITLE
[PE-D][Tester D] Command words are too long to be used efficiently

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T17-4/tp#203]
Having to type `patients` or `appts` for a majority of the commands is not very efficient, even for fast typists, due to the repetitive nature. Something like `pa` and `ap` should have been used instead.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: jetlfj/ped#4

**Comment by JovonLim** [comment]
This is a suggestion for our feature flaw, but we are unable to work on it in v1.4. Hence have to ignore
