### ISSUE TITLE
[PE-D][Tester B] edit appts functionality bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T17-4/tp#204]
Mentioned that can use edit appts 1 t/ to remove all tags however did not mention that edit appts 1 pe/ can also change from recurring to non recurring.

![image.png](https://raw.githubusercontent.com/Marcusgwj/ped/main/files/dcd42c65-3da2-4b85-8a56-2d4436f6f451.png)

![image.png](https://raw.githubusercontent.com/Marcusgwj/ped/main/files/9a0f3bf2-198b-4818-959f-3940177c7450.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Marcusgwj/ped#4

**Comment by Guanzhou03** [comment]
Not sure if this is even a bug since it's not a specified/promised behavior. But we should all look into error handling of invalid/empty inputs in the commands

**Comment by NicholasTYD** [comment]
This should be a user guide bug
