### ISSUE TITLE
[PE-D][Tester D] Unclear how grouping of patients is done and how they are sorted

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T17-4/tp#205]
Grouping patients seems to put them together if they have the exact same tags but this is not documented and it is unclear how the groups are sorted in the list.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: jetlfj/ped#5

**Comment by WingKei67** [comment]
I think our document has mentioned its function: 'Shows a list of all patients grouped by their tags.', and I don't think users need to know how this feature is implemented. Not sure what the bug is.
