### ISSUE TITLE
[PE-D][Tester B] delete example

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T17-4/tp#206]
Team forgot to indent second delete example 

![image.png](https://raw.githubusercontent.com/Marcusgwj/ped/main/files/75913f81-b561-431c-be35-2d0535e2b0b9.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Marcusgwj/ped#5

**Comment by Guanzhou03** [comment]
Minor documentation bug, although it looks like the endIndex should also be changed to END_INDEX to standardize the format.
