### ISSUE TITLE
[PE-D][Tester E] Hide command does not recognise invalid tags

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T17-4/tp#208]
The user guide states the following:

> Tag names must only be from the following: ear, nose, throat (not case-sensitive).
e.g. t/sick will cause an error message.

However, this rule is not followed for the hide command. Upon using an invalid tag like `t/brain`, no error message is returned. This may mislead users into thinking that this tag is valid.

![image.png](https://raw.githubusercontent.com/zacchaeuschok/ped/main/files/eb266e73-56d1-48f0-829b-5a0380d31c6a.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: zacchaeuschok/ped#3

**Comment by Guanzhou03** [comment]
A simple check for valid tag in the parser will resolve this
