### ISSUE TITLE
[PE-D][Tester B] Same patient criteria

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T17-4/tp#216]
Would be good to specify what's considered the same patient. Able to add a patient with only diff number but not with only diff address. Good to specify rationale as well.

![image.png](https://raw.githubusercontent.com/Marcusgwj/ped/main/files/dfd6c9b2-cf4f-4267-8a8a-37bc8936ff55.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Marcusgwj/ped#10

**Comment by Guanzhou03** [comment]
Maybe we can specify in the UG that we allow same names, but not the same number as two distinct people cannot have the same phone number.

**Comment by WingKei67** [comment]
Agreed. I think we can make a Q&A section about duplicate names and make hyperlinks linked to it. Hyperlinks will be added to all commands that update names (add and edit).
