### ISSUE TITLE
[PE-D][Tester E] Tags in patients do not correspond with tags in appointments

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T17-4/tp#218]
For the product's intended purpose and target audience, it should make sense for the tags in patients to reflect all the tags in appointments, since they are being treated for those conditions. 

![image.png](https://raw.githubusercontent.com/zacchaeuschok/ped/main/files/12b87e31-22bd-4ffb-9d18-fcbf88dbd95d.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: zacchaeuschok/ped#5

**Comment by Guanzhou03** [comment]
Need to discuss on what tags mean for patients/appointments, should they necessarily be the same? Or perhaps patient/appointment tags need not simply be nose/ear/throat
