### ISSUE TITLE
[PE-D][Tester D] Unhide command format in the command summary does not match the actual command format

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T17-4/tp#219]
![image.png](https://raw.githubusercontent.com/jetlfj/ped/main/files/1b0b119a-dad4-4cf2-805b-c0b38bbe9857.png)

The correct command format is `unhide appts CONDITION`, not `unhide appointments CONDITION` as shown here in the command summary.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: jetlfj/ped#7

**Comment by pwjj2000** [comment]
I thought we already changed this lol. Nevertheless easy change on our part.
