### ISSUE TITLE
[PE-D][Tester B] Formatting in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T17-4/tp#221]
Texts can be rather long due to different features

Would be good to apply some formatting to make it easier for the reader to identify each subsection

Eg bolding By reason, By tag etc

![image.png](https://raw.githubusercontent.com/Marcusgwj/ped/main/files/1e92e1fc-f963-4722-82bf-f6ae30a1e0d1.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: Marcusgwj/ped#12

**Comment by pwjj2000** [comment]
I think this is good. We can bold or underline the parts indicated by the tester.
