### ISSUE TITLE
[PE-D][Tester B] Images in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T17-4/tp#223]
Would be good to add more images to UG such as for group and hide function which may be harder for a new user to understand.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: Marcusgwj/ped#13

**Comment by JovonLim** [comment]
Agree with this, should act more images for our organisation commands

**Comment by WingKei67** [comment]
Agreed. Additionally, we can elaborate our command descriptions a bit more.
