### ISSUE TITLE
[PE-D][Tester D] Unclear how hiding works with multiple keywords

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T17-4/tp#226]
![image.png](https://raw.githubusercontent.com/jetlfj/ped/main/files/9baf0142-4d7b-44e5-a884-64441ca5db85.png)

If multiple keywords are provided, it is unclear which appointments will be hidden. Ones that have a least one of the keywords or ones that have all of the keywords?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jetlfj/ped#9

**Comment by pwjj2000** [comment]
Current implementation is "at least one of the keywords". Propose we amend the command description to specify this, and also include examples with more than 1 `/r`
